# What is TensorFlow?

![](https://upload.wikimedia.org/wikipedia/commons/a/a4/TensorFlowLogo.png)


TensorFlow is an open source software library released in 2015 by Google to make it easier for developers to design, build, and train deep learning models. TensorFlow originated as an internal library that Google developers used to build models in-house, and we expect additional functionality to be added to the open source version as they are tested and vetted in the internal flavor. Although TensorFlow is only one of several options available to developers, we choose to use it here because of its thoughtful design and ease of use. We’ll briefly compare TensorFlow to alternatives in the next section.

At a high level, TensorFlow is a Python library that allows users to express arbitrary computation as a graph of data flows. Nodes in this graph represent mathematical operations, whereas edges represent data that is communicated from one node to another. Data in TensorFlow are represented as tensors, which are multidimensional arrays. Although this framework for thinking about computation is valuable in many different fields, TensorFlow is primarily used for deep learning in practice and research.



## Install
As usual, we'll be using Conda to install TensorFlow. You might already have a TensorFlow environment, but check to make sure you have all the necessary packages.

### OS X or Linux
Run the following commands to setup your environment:

    conda create -n tensorflow python=3.5
    source activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Windows
And installing on Windows. In your console or Anaconda shell,

    conda create -n tensorflow python=3.5
    activate tensorflow
    conda install pandas matplotlib jupyter notebook scipy scikit-learn
    pip install tensorflow

### Hello, world!
Try running the following code in your Python console to make sure you have TensorFlow properly installed. The console will print "Hello, world!" if TensorFlow is installed. Don’t worry about understanding what it does. You’ll learn about it in the next section.



#### !pip install tensorflow==1.14.0

In [4]:
import tensorflow as tf

In [5]:
tf.__version__

'1.14.0'

### Creating Different kind of Variables as Tensors

### tf.constant()
#### Constant will not be changed at anypoint of time (even at runtime)

In [6]:
hello_constant = tf.constant('Hello World!')
hello_constant

<tf.Tensor 'Const_2:0' shape=() dtype=string>

##### Tensorflow follows Lazy Evaluation .
##### So eventhough we print the variable it will not give the output in the Console

In [7]:
hello_constant = tf.constant(35200)
hello_constant

<tf.Tensor 'Const_3:0' shape=() dtype=int32>

#### Then How to access the data in Tensorflow ??
#### By calling the data in a Session

In [10]:
a = tf.constant('SC20M104')
a

<tf.Tensor 'Const_6:0' shape=() dtype=string>

### tf.Session()
### tf.Session().run(variable)
#### Each and Every operation can be Performed only in Session()

In [9]:
a = tf.constant('SC20M104')
print(tf.Session().run(a))

b'SC20M104'


In [8]:
import tensorflow as tf

# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
        # Run the tf.constant operation in the session
        output = sess.run(hello_constant)
        print(output)

b'Hello World!'


##### Tensorflow 1.0 Requires tf.Session() to access the data 
##### Tensorflow 2.0 doesn't have the concept as Session()

Let’s analyze the Hello World script you ran. 

### Tensor
In TensorFlow, data isn’t stored as integers, floats, or strings. These values are encapsulated in an object called a tensor. In the case of hello_constant = tf.constant('Hello World!'), hello_constant is a 0-dimensional string tensor, but tensors come in a variety of sizes as shown below:

#### a constant variable can be created with an integer or with a List or with a Nested List

In [24]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234)
print(A)
print("A holds a Constant ",tf.Session().run(A))
print(" ")

# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789])
print(B)
print("B holds a List ",tf.Session().run(B))
print(" ")

# C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])
print(C)
print("C holds a Nested List ",tf.Session().run(C))

Tensor("Const_43:0", shape=(), dtype=int32)
A holds a Constant  1234
 
Tensor("Const_44:0", shape=(3,), dtype=int32)
B holds a List  [123 456 789]
 
Tensor("Const_45:0", shape=(2, 3), dtype=int32)
C holds a Nested List  [[123 456 789]
 [222 333 444]]


In [12]:
C 

<tf.Tensor 'Const_9:0' shape=(2, 3) dtype=int32>

tf.constant() is one of many TensorFlow operations you will use in this lesson. The tensor returned by tf.constant() is called a constant tensor, because the value of the tensor never changes.

### Session

TensorFlow’s api is built around the idea of a computational graph, a way of visualizing a mathematical process.  Let’s take the TensorFlow code and turn that into a graph:

![Session](https://d17h27t6h515a5.cloudfront.net/topher/2016/October/580feadb_session/session.png)

A "TensorFlow Session", as shown above, is an environment for running a graph. The session is in charge of allocating the operations to GPU(s) and/or CPU(s), including remote machines. Let’s see how you use it:

In [25]:
with tf.Session() as sess:
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


### tf.constant() and tf.placeholder()
#### tf.constant() : Pass the Data ath the Time of Variable Creation
#### tf.placeholder() : Just give the Datatype of the Data at the Time of Variable Creation.And the Data of Same Data type can be Passed at the Run TIme

In [26]:
x = tf.constant(12345)
x = tf.placeholder(tf.string)

The code has already created the tensor, `hello_constant`, from the previous lines. The next step is to evaluate the tensor in a session.

The code creates a session instance, `sess`, using `tf.Session`. The `sess.run()` function then evaluates the tensor and returns the results.

## TensorFlow Input 

In the last section, a tensor was passed into a session and it returned the result. What if we want to use a non-constant? This is where `tf.placeholder()` and `feed_dict` come into place. In this section, we'll go over the basics of feeding data into TensorFlow.

### tf.placeholder()

Sadly you can’t just set `x` to your dataset and put it in TensorFlow, because over time you'll want your TensorFlow model to take in different datasets with different parameters. You need `tf.placeholder()`!

`tf.placeholder()` returns a tensor that gets its value from data passed to the `tf.session.run()` function, allowing you to set the input right before the session runs.

### Session's feed_dict

#### Creating a Variable using placeholder() and passing Datatype

In [29]:
x = tf.placeholder(tf.string)

#### Calling the Created Variable in a Session and passing the Data of SAME DATA TYPE at Runtime using a Dictionary [i,e Key : Value ]

In [36]:
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Bharadwaj'})
    print(output)

Bharadwaj


#### Error : Calling the Created Variable in a Session and passing the Data of DIFFERENT DATA TYPE at Runtime using a Dictionary [i,e Key : Value ]

In [31]:
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 1234})
    print(output)

TypeError: Type of feed value 1234 with type <class 'int'> is not compatible with Tensor type <class 'object'>. Try explicitly setting the type of the feed tensor to a larger type (e.g. int64).

In [37]:
x = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 81.3542})
    print(output)

81.3542


Use the feed_dict parameter in `tf.session.run()` to set the placeholder tensor. The above example shows the tensor `x` being set to the string `"Hello, world"`. It's also possible to set more than one tensor using `feed_dict` as shown below:

### In tf.Session() we can give any number of run()

#### For a tf.placeholder() , When we are passing the Data at the Runtime through a feed_dict= { } . It will Extract the Data only from the Same Key [as the Variable Created] in the feed_dict 

In [43]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x,feed_dict={x: 'Test String', y: 123, z: 45.67})
    output_y = sess.run(y, feed_dict={x: 'Test String', y: 123, z:45.67})
    print("The value is taken from Key x ",output_x)
    print("The value is taken from Key y ",output_y)

The value is taken from Key x  Test String
The value is taken from Key y  123


In [44]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x,feed_dict={x: 'Test String'})
    output_y = sess.run(y, feed_dict={ y: 123})
    print("The value is taken from Key x ",output_x)
    print("The value is taken from Key y ",output_y)

The value is taken from Key x  Test String
The value is taken from Key y  123


### Error : If feed_dict doen't have a key same as variable created using tf.placeholder()

In [45]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x,feed_dict={y: 'Test String'})
    output_y = sess.run(y, feed_dict={ x: 123})
    print("The value is taken from Key x ",output_x)
    print("The value is taken from Key y ",output_y)

ValueError: invalid literal for int() with base 10: 'Test String'

**Note**: If the data passed to the `feed_dict` doesn’t match the tensor type and can’t be cast into the tensor type, you’ll get the error `“ValueError: invalid literal for...”`.


## TensorFlow Math

Getting the input is great, but now you need to use it. We're going to use basic math functions that everyone knows and loves - add, subtract, multiply, and divide - with tensors. (There's many more math functions you can check out in the [documentation](https://www.tensorflow.org/api_docs/python/math_ops/).)

### Addition

In [47]:
x = tf.add(5, 2)
x

<tf.Tensor 'Add_1:0' shape=() dtype=int32>

In [48]:
with tf.Session() as sess:
    output = sess.run(x)
    print(output)

7


In [52]:
print(tf.Session().run(x))

7


Let's start with the add function. The `tf.add()` function does exactly what you expect it to do. It takes in two numbers, two tensors, or one of each, and returns their sum as a tensor.

### Subraction and Multiplication

In [53]:
x = tf.subtract(10, 4) # 6
y = tf.multiply(2, 5)  # 10

In [56]:
with tf.Session() as sess:
    Sub = sess.run(x)
    print("Substraction :",Sub)
    Mul = sess.run(y)
    print("Multiplication :",Mul)


Substraction : 6
Multiplication : 10


The `x` tensor will evaluate to `6`, because `10 - 4 = 6`. The `y` tensor will evaluate to `10`, because `2 * 5 = 10`. That was easy!

### Converting Types

It may be necessary to convert between types to make certain operators work together. For example, if you tried the following, it would fail with an exception:

In [57]:
2.0 - 1

1.0

### To perform any operation in Tensorflow , Same Datatype and Even Same bits should be taken.
### Valid Examples :
#### int32 and int32
#### float64 and float64
### invalid Examples :
#### int32 and int64
#### int32 and float32

In [35]:
tf.subtract(tf.constant(2.0),tf.constant(1))  

TypeError: Input 'y' of 'Sub' Op has type int32 that does not match type float32 of argument 'x'.

That's because the constant `1` is an integer but the constant `2.0` is a floating point value and subtract expects them to match.

In cases like these, you can either make sure your data is all of the same type, or you can cast a value to another type. In this case, converting the `2.0` to an integer before subtracting, like so, will give the correct result:

### tf.cast() overcome the above Error  
### tf.cast() : Used for typecasting

In [60]:
c = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))   # 1
c

<tf.Tensor 'Sub_2:0' shape=() dtype=int32>

In [59]:
with tf.Session() as sess:
    output = sess.run(c)
    print(output)

1


### Example

Let's apply what you learned to convert an algorithm to TensorFlow. The code below is a simple algorithm using division and subtraction. Convert the following algorithm in regular Python to TensorFlow and print the results of the session. You can use `tf.constant()` for the values `10`, `2`, and `1`.

In [61]:
import tensorflow as tf


x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x, y), 1)


with tf.Session() as sess:
    output = sess.run(z)
    print(output)


4.0


## TensorFlow Linear Functions

The most common operation in neural networks is calculating the linear combination of inputs, weights, and biases. As a reminder, we can write the output of the linear operation as:

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58a4d8b3_linear-equation/linear-equation.gif)

Here, **W** is a matrix of the weights connecting two layers. The output **y**, the input **x**, and the biases **b** are all vectors.

### Weights and Bias in TensorFlow

The goal of training a neural network is to modify weights and biases to best predict the labels. In order to use weights and bias, you'll need a Tensor that can be modified. This leaves out `tf.placeholder()` and `tf.constant()`, since those Tensors can't be modified. This is where `tf.Variable` class comes in.


### tf.Variable() : We'll intialize with some data at Declaration and we can also able to Change it at Run time

#### Example : Like weights in Neural network
#### At beginning we'll intialize weights with Random Number and Later after backpropogation , we'll update Weights

In [63]:
x = tf.Variable(5)

The `tf.Variable` class creates a tensor with an initial value that can be modified, much like a normal Python variable. This tensor stores its state in the session, so you must initialize the state of the tensor manually. You'll use the `tf.global_variables_initializer()` function to initialize the state of all the Variable tensors:

### Only in tensorflow 1.X 
### we have to call tf.global_variables_initializer() inorder to peform operations on tf.Variable()

In [67]:
x = tf.Variable(5)

In [68]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))

5


The `tf.global_variables_initializer()` call returns an operation that will initialize all TensorFlow variables from the graph. You call the operation using a session to initialize all the variables as shown above. Using the `tf.Variable` class allows us to change the weights and bias, but an initial value needs to be chosen.

Initializing the weights with random numbers from a normal distribution is good practice. Randomizing the weights helps the model from becoming stuck in the same place every time you train it. You'll learn more about this in the next lesson, gradient descent.

Similarly, choosing weights from a normal distribution prevents any one weight from overwhelming other weights. We'll use the `tf.truncated_normal()` function to generate random numbers from a normal distribution.

### tf.truncated_normal()

In [73]:
n_features = 10
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
weights

<tf.Variable 'Variable_5:0' shape=(10, 5) dtype=float32_ref>

In [74]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(weights))

[[-1.9667537  -0.6010964  -1.0617123  -0.01933837  1.0978818 ]
 [ 0.24278717 -0.60136664  1.1143359  -0.85366565 -1.2932298 ]
 [ 1.4465522  -0.34615698 -1.6407151  -0.8579116  -0.7794554 ]
 [-0.94399595 -0.23696394 -0.1267269  -1.285525   -0.25257382]
 [ 1.1453295  -0.52485913  1.495702    0.73380667  1.6949483 ]
 [ 0.43652704  0.5119081   0.137321   -0.95559084  0.22829026]
 [ 1.0299903  -1.2928585  -1.2479899  -0.27370998  0.86636686]
 [-0.86512077 -0.48460597 -0.7735382  -0.4269564   0.767872  ]
 [-0.02401555 -0.3227105  -1.5076036   1.2441639  -0.46758407]
 [-0.5800251   0.00346466 -1.5927653   1.2081707  -0.15911233]]


#### Example : mth Layer = 10 Neurons and (m+1)th Layer = 5 Neurons
#### Size of the weight matrix between mth and (m+1)th Layer = 5 * 10

In [75]:
n_features = 5
n_labels = 10
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
weights

<tf.Variable 'Variable_6:0' shape=(5, 10) dtype=float32_ref>

In [76]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(weights))

[[ 0.45866507  0.59853286  0.5483433  -1.3558229  -0.23725     0.81914896
   0.22065765 -0.24521908  1.378223    0.90303123]
 [-0.74461323 -0.23705396  0.01439435 -1.9462888  -0.63374746  1.6374481
  -0.3701079   0.49650294 -0.02933039 -0.04547245]
 [ 0.96411115 -1.413693    0.7767121  -0.8963733  -0.6056933   0.99513876
  -1.2410779  -1.6941812   1.0581136   0.40363002]
 [ 0.93457735 -0.84964347 -0.05256181 -0.55410206  0.81079644 -0.3241666
   0.18464501  1.1815039   0.8386395   0.6343719 ]
 [-0.28841645 -0.57986176 -0.76362157 -0.5508392   0.7967287   0.25788927
  -1.1795001  -0.38980135  1.0089223   0.33090827]]


The `tf.truncated_normal()` function returns a tensor with random values from a normal distribution whose magnitude is no more than 2 standard deviations from the mean.

Since the weights are already helping prevent the model from getting stuck, you don't need to randomize the bias. Let's use the simplest solution, setting the bias to 0.

### tf.zeros()
#### The `tf.zeros()` function returns a tensor with all zeros.

In [78]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))
bias

<tf.Variable 'Variable_8:0' shape=(5,) dtype=float32_ref>

In [79]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(bias))

[0. 0. 0. 0. 0.]


### tf.ones()
#### The `tf.ones()` function returns a tensor with all ones.

In [81]:
n_labels = 5
bias = tf.Variable(tf.ones(n_labels))
bias

<tf.Variable 'Variable_10:0' shape=(5,) dtype=float32_ref>

In [82]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(bias))

[1. 1. 1. 1. 1.]




## TensorFlow Softmax

The softmax function squashes it's inputs, typically called **logits** or **logit scores**, to be between 0 and 1 and also normalizes the outputs such that they all sum to 1. This means the output of the softmax function is equivalent to a categorical probability distribution. It's the perfect function to use as the output activation for a network predicting multiple classes.

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/58950908_softmax-input-output/softmax-input-output.png)

We're using TensorFlow to build neural networks and, appropriately, there's a function for calculating softmax.

In [97]:
x = tf.nn.softmax([1.2, 0.9, 0.4])
x

<tf.Tensor 'Softmax_4:0' shape=(3,) dtype=float32>

In [98]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(x))
    print("Sum :",sess.run(tf.math.reduce_sum(x)))

[0.45659032 0.3382504  0.20515925]
Sum : 0.99999994


Easy as that! `tf.nn.softmax()` implements the softmax function for you. It takes in logits and returns softmax activations.

### Example

In [2]:
import tensorflow as tf


def run_2():
    output = None
    logit_data = [19,354,354,45,354,54]
    logits = tf.placeholder(tf.float32)
    
    # Calculate the softmax of the logits
    softmax = tf.nn.softmax(logits)   
    
    with tf.Session() as sess:
        # Feed in the logit data
        output = sess.run(softmax, feed_dict={logits: logit_data})
        print("Sum :",sess.run(tf.math.reduce_sum(output)))
    return output

print(run_2())


Sum : 1.0
[0.         0.33333334 0.33333334 0.         0.33333334 0.        ]


### Label-Encoding
#### The problem with Label-Encoding : the Output is a Biased 

In [10]:
import numpy as np
from sklearn import preprocessing

# Exampl Labels
# labels = np.array([1,5,3,2,1,4,2,1,3])
labels = np.array(["A","B","C","D","A","A","B","C"])

# Create the Encoder
lb = preprocessing.LabelEncoder()

# Here the Encoder finds the classes and assigns one-hot Vectos
lb.fit(labels)

# Finally Transform the Labels into one-hot Encoded Vectots
lb.transform(labels)

array([0, 1, 2, 3, 0, 0, 1, 2], dtype=int64)

## One-Hot Encoding

Transforming your labels into one-hot encoded vectors is pretty simple with scikit-learn using `LabelBinarizer`. Check it out below!

In [11]:
import numpy as np
from sklearn import preprocessing

# Exampl Labels
# labels = np.array([1,5,3,2,1,4,2,1,3])
labels = np.array(["A","B","C","D","A","A","B","C"])

# Create the Encoder
lb = preprocessing.LabelBinarizer()

# Here the Encoder finds the classes and assigns one-hot Vectos
lb.fit(labels)

# Finally Transform the Labels into one-hot Encoded Vectots
lb.transform(labels)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

## TensorFlow Cross Entropy

In the Intro to TFLearn lesson we discussed using cross entropy as the cost function for classification with one-hot encoded labels. Again, TensorFlow has a function to do the cross entropy calculations for us.

![](https://d17h27t6h515a5.cloudfront.net/topher/2017/February/589b18f5_cross-entropy-diagram/cross-entropy-diagram.png)

To create a cross entropy function in TensorFlow, you'll need to use two new functions:

* `tf.reduce_sum()`
* `tf.log()`

### Reduce Sum

In [12]:
x = tf.reduce_sum([1, 2, 3, 4, 5])  # 15
print(tf.Session().run(x))

15


The `tf.reduce_sum()` function takes an array of numbers and sums them together.

### Natural Log

In [13]:
l = tf.log(100.0)  # 4.60517
print(tf.Session().run(l))

4.6051702


This function does exactly what you would expect it to do. `tf.log()` takes the natural log of a number.

### Example

Print the cross entropy using `softmax_data` and `one_hot_encod_label`.

In [62]:
import tensorflow as tf

softmax_data = [0.7, 0.2, 0.1]
one_hot_data = [1.0, 0.0, 0.0]

softmax = tf.placeholder(tf.float32)
one_hot = tf.placeholder(tf.float32)

# Print cross entropy from session
cross_entropy = -tf.reduce_sum(tf.multiply(one_hot, tf.log(softmax)))

with tf.Session() as session:
    output = session.run(cross_entropy, feed_dict={one_hot: one_hot_data, softmax: softmax_data})
    print(output)


0.35667497


## Mini-batching


Mini-batching is a technique for training on subsets of the dataset instead of all the data at one time. This provides the ability to train a model, even if a computer lacks the memory to store the entire dataset.

Mini-batching is computationally inefficient, since you can't calculate the loss simultaneously across all samples. However, this is a small price to pay in order to be able to run the model at all.

It's also quite useful combined with SGD. The idea is to randomly shuffle the data at the start of each epoch, then create the mini-batches. For each mini-batch, you train the network weights with gradient descent. Since these batches are random, you're performing SGD with each batch.



## Epochs

An epoch is a single forward and backward pass of the whole dataset. This is used to increase the accuracy of the model without requiring more data. 